Repository Theseus-Aegis/Mods, pull requests merged in 2018-12, with the labels that each got.

#371 Add extension support for retrieving accessible item classes
  Makefile
  addons/apollo/script_component.hpp
  extensions/src/apollo_client/dllmain.cpp
  extensions/src/common/version.h
  tac_apollo_client.dll
  tac_apollo_client_x64.dll
Labels: feature request

#369 Compat - add project infinite compat
  make.bat
  optionals/bnae_falkor_compat_ace/$PBOPREFIX$
  optionals/bnae_falkor_compat_ace/CfgAmmo.hpp
  optionals/bnae_falkor_compat_ace/CfgMagazines.hpp
  optionals/bnae_falkor_compat_ace/CfgWeapons.hpp
  optionals/bnae_falkor_compat_ace/README.md
  optionals/bnae_falkor_compat_ace/config.cpp
  optionals/bnae_falkor_compat_ace/script_component.hpp
  optionals/bnae_mk1_compat_ace/$PBOPREFIX$
  optionals/bnae_mk1_compat_ace/CfgAmmo.hpp
  optionals/bnae_mk1_compat_ace/CfgMagazines.hpp
  optionals/bnae_mk1_compat_ace/CfgWeapons.hpp
  optionals/bnae_mk1_compat_ace/README.md
  optionals/bnae_mk1_compat_ace/config.cpp
  optionals/bnae_mk1_compat_ace/script_component.hpp
  optionals/bnae_rk95_compat_ace/$PBOPREFIX$
  optionals/bnae_rk95_compat_ace/CfgAmmo.hpp
  optionals/bnae_rk95_compat_ace/CfgMagazines.hpp
  optionals/bnae_rk95_compat_ace/CfgWeapons.hpp
  optionals/bnae_rk95_compat_ace/README.md
  optionals/bnae_rk95_compat_ace/config.cpp
  optionals/bnae_rk95_compat_ace/script_component.hpp
  optionals/bnae_trg42_compat_ace/$PBOPREFIX$
  optionals/bnae_trg42_compat_ace/CfgAmmo.hpp
  optionals/bnae_trg42_compat_ace/CfgMagazines.hpp
  optionals/bnae_trg42_compat_ace/CfgWeapons.hpp
  optionals/bnae_trg42_compat_ace/README.md
  optionals/bnae_trg42_compat_ace/config.cpp
  optionals/bnae_trg42_compat_ace/script_component.hpp
Labels: compatibility, feature request

#372 Remove ACRE2 Compatibility for CUP Land Rovers
  optionals/cup_vehicles_acre_racks/CfgVehicles.hpp
  optionals/cup_vehicles_acre_racks/config.cpp
Labels: cleanup

#359 Add painkillers
  addons/medical/$PBOPREFIX$
  addons/medical/ACE_Medical_Actions.hpp
  addons/medical/CfgVehicles.hpp
  addons/medical/CfgWeapons.hpp
  addons/medical/README.md
  addons/medical/config.cpp
  addons/medical/script_component.hpp
  addons/medical/stringtable.xml
  addons/medical/ui/painkillers_icon_ca.paa
  addons/medical/ui/painkillers_inventory_ca.paa
Labels: feature request
