Repository Theseus-Aegis/Mods, pull requests merged in 2018-08, with the labels that each got.

#364 Added ACRE2 radio racks to Qilin, Prowler, SUV, EagleIV & Land Rover
  optionals/a3_acre_racks/$PBOPREFIX$
  optionals/a3_acre_racks/CfgVehicles.hpp
  optionals/a3_acre_racks/README.md
  optionals/a3_acre_racks/config.cpp
  optionals/a3_acre_racks/script_component.hpp
  optionals/bwa_acre_racks/$PBOPREFIX$
  optionals/bwa_acre_racks/CfgVehicles.hpp
  optionals/bwa_acre_racks/README.md
  optionals/bwa_acre_racks/config.cpp
  optionals/bwa_acre_racks/script_component.hpp
  optionals/cup_vehicles_acre_racks/$PBOPREFIX$
  optionals/cup_vehicles_acre_racks/CfgVehicles.hpp
  optionals/cup_vehicles_acre_racks/README.md
  optionals/cup_vehicles_acre_racks/config.cpp
  optionals/cup_vehicles_acre_racks/script_component.hpp
  optionals/milgp_ace_hearing/README.md
Labels: feature request

#365 Update Heavy Lifter definitions for Arma 3 v1.84 and CUP 1.10.1
  addons/heavylifter/CfgVehicles.hpp
  addons/heavylifter/functions/fnc_exportConfig.sqf
  optionals/compat_cup_vehicles/CfgVehicles.hpp
  optionals/compat_cup_vehicles/config.cpp
Labels: compatibility, task

#366 Remove Mission Autotest Eden Attributes conditions (RPT error, unneeded)
  addons/mission_autotest/CfgEden.hpp
Labels: bug fix
