Repository Theseus-Aegis/Mods, pull requests merged in 2019-11, with the labels that each got.

#399 Update Medical settings for ACE3 Medical Rewrite
  addons/cba_settings/cba_settings.sqf
Labels: compatibility, setting

#404 Almost completely finished German
  addons/armory/stringtable.xml
  addons/medical/stringtable.xml
  addons/mission_autotest/stringtable.xml
Labels: translation

#393 Update painkillers for ACE3 Medical Rewrite
  addons/medical/ACE_Medical_Actions.hpp
  addons/medical/CfgVehicles.hpp
  addons/medical/config.cpp
Labels: compatibility

#416 Fix No Actions descriptions and Remove No Rearm
  addons/noactions/CfgActions.hpp
  addons/noactions/README.md
  addons/noactions/initSettings.sqf
  addons/noactions/stringtable.xml
Labels: bug fix, cleanup

#415 Improve ACE3 Medical Rewrite Settings
  addons/cba_settings/cba_settings.sqf
Labels: bug fix, setting

#414 Default to 1 item take quantity in Armory
  addons/armory/functions/fnc_dialogControl_amountSelection.sqf
Labels: enhancement
