Repository Theseus-Aegis/Mods, pull requests merged in 2019-10, with the labels that each got.

#403 Use non-command variable name for Shooting Range score
  addons/shootingrange/functions/fnc_handleHitPart.sqf
  addons/shootingrange/functions/fnc_popupPFH.sqf
  addons/shootingrange/functions/fnc_popupPFHexit.sqf
  addons/shootingrange/functions/fnc_start.sqf
Labels: cleanup

#400 Add Arma CI Workflow (validate, lint, build)
  .github/workflows/arma.yml
  .travis.yml
  addons/air_security/stringtable.xml
  addons/apollo/stringtable.xml
  addons/armory/stringtable.xml
  addons/bodybag/stringtable.xml
  addons/heavylifter/stringtable.xml
  addons/insignia/stringtable.xml
  addons/main/stringtable.xml
  addons/medical/stringtable.xml
  addons/mission_autotest/stringtable.xml
Labels: tools

#405 Add Documentation CI Workflow (translations)
  .github/workflows/main.yml
  .travis.yml
Labels: tools

#406 Update HEMTT configuration for 0.7.0 (restructure)
  .github/workflows/arma.yml
  .gitignore
  README.md
  hemtt.toml
Labels: tools

#408 Switch disposable launchers to base variant on Armory stash
  addons/apollo/functions/fnc_lockerAction.sqf
  addons/armory/functions/fnc_getBaseVariant.sqf
  addons/armory/functions/fnc_processAction.sqf
Labels: bug fix, compatibility

#410 Default to max item stash quantity in Armory
  addons/armory/functions/fnc_dialogControl_amountSelection.sqf
Labels: enhancement

#411 Fix Armory full refresh wiping item list
  addons/armory/XEH_postInitClient.sqf
Labels: bug fix

#412 Update Heavy Lifter definitions for Arma 3 1.96 and CUP 1.13.0
  addons/heavylifter/CfgVehicles.hpp
  optionals/compat_cup_vehicles/CfgVehicles.hpp
Labels: compatibility, task

#407 Add NoActions component
  AUTHORS.txt
  addons/noactions/$PBOPREFIX$
  addons/noactions/CfgActions.hpp
  addons/noactions/CfgEventHandlers.hpp
  addons/noactions/README.md
  addons/noactions/XEH_preInit.sqf
  addons/noactions/config.cpp
  addons/noactions/initSettings.sqf
  addons/noactions/script_component.hpp
  addons/noactions/stringtable.xml
Labels: feature request
