Repository Theseus-Aegis/Mods, pull requests merged in 2019-02, with the labels that each got.

#379 [Compat] Fix ACE magazines being overwritten and UBC warnings
  optionals/bnae_falkor_compat_ace/CfgAmmo.hpp
  optionals/bnae_falkor_compat_ace/CfgMagazines.hpp
  optionals/bnae_falkor_compat_ace/config.cpp
  optionals/bnae_mk1_compat_ace/CfgAmmo.hpp
  optionals/bnae_mk1_compat_ace/CfgMagazines.hpp
  optionals/bnae_mk1_compat_ace/config.cpp
  optionals/bnae_rk95_compat_ace/CfgAmmo.hpp
  optionals/bnae_rk95_compat_ace/CfgMagazines.hpp
  optionals/bnae_rk95_compat_ace/CfgWeapons.hpp
  optionals/bnae_rk95_compat_ace/config.cpp
  optionals/bnae_trg42_compat_ace/CfgAmmo.hpp
  optionals/bnae_trg42_compat_ace/CfgMagazines.hpp
  optionals/bnae_trg42_compat_ace/config.cpp
Labels: bug fix, compatibility

#378 Add Sling-Load locality improvement
  addons/slingload/$PBOPREFIX$
  addons/slingload/CfgEventHandlers.hpp
  addons/slingload/README.md
  addons/slingload/XEH_postInitServer.sqf
  addons/slingload/config.cpp
  addons/slingload/script_component.hpp
Labels: feature request, needs testing

#380 Update Heavy Lifter and No Uniform Restrictions definitions for Arma 3 1.88 and CUP 1.11.1
  addons/heavylifter/CfgVehicles.hpp
  optionals/compat_cup_vehicles/CfgVehicles.hpp
  optionals/compat_cup_vehicles/config.cpp
  optionals/cup_units_nouniformrestrictions/CfgVehicles.hpp
Labels: bug fix, compatibility, task

#377 Allow nil targets on Shooting Range
  addons/shootingrange/functions/fnc_create.sqf
  addons/shootingrange/functions/fnc_moduleInit.sqf
  addons/shootingrange/functions/fnc_setTargetGroups.sqf
  addons/shootingrange/functions/fnc_stop.sqf
  addons/shootingrange/script_component.hpp
Labels: enhancement
