Repository Theseus-Aegis/Mods, pull requests merged in 2020-10, with the labels that each got.

#459 Add min/max to the HC amount autocheck
  addons/mission_autotest/functions/fnc_testHCAmount.sqf
  addons/mission_autotest/script_component.hpp
Labels: enhancement

#460 Add Optional MELB Tweaks
  optionals/melb_tweaks/$PBOPREFIX$
  optionals/melb_tweaks/CfgAmmo.hpp
  optionals/melb_tweaks/CfgMagazines.hpp
  optionals/melb_tweaks/CfgWeapons.hpp
  optionals/melb_tweaks/README.md
  optionals/melb_tweaks/config.cpp
  optionals/melb_tweaks/script_component.hpp
Labels: feature request

#461 Fix Armory combined CBA Scripted Optic and Accessory variant switch
  addons/armory/dev/test_baseVariants.sqf
  addons/armory/functions/fnc_getBaseVariant.sqf
Labels: bug fix, tools

#463 Add Gridlines to FRL Kunduz
  optionals/kunduz_gridlines/$PBOPREFIX$
  optionals/kunduz_gridlines/CfgWorlds.hpp
  optionals/kunduz_gridlines/README.md
  optionals/kunduz_gridlines/config.cpp
  optionals/kunduz_gridlines/script_component.hpp
Labels: feature request

#464 Fix Boost compatibility with newer CMake
  README.md
  extensions/CMakeLists.txt
  extensions/CMakeModules/FindBoost.cmake
Labels: bug fix, ignore changelog, tools
