Repository Theseus-Aegis/Mods, pull requests merged in 2020-04, with the labels that each got.

#434 Settings - Set ACE3 Medical Medic IV to Anyone
  addons/cba_settings/cba_settings.sqf
Labels: setting

#437 Update Blastcore to updated Standalone in Check PBOs Whitelist
  addons/cba_settings/cba_settings.sqf
Labels: enhancement

#436 Add Optional CUP ACE3 Hearing Compatibility
  optionals/cup_ace_hearing/$PBOPREFIX$
  optionals/cup_ace_hearing/CfgWeapons.hpp
  optionals/cup_ace_hearing/README.md
  optionals/cup_ace_hearing/config.cpp
  optionals/cup_ace_hearing/script_component.hpp
Labels: compatibility, feature request
