Repository Theseus-Aegis/Mods, pull requests merged in 2020-05, with the labels that each got.

#439 Add Earplugs to Apollo and use new ACRE2 filter unit loadout API
  addons/apollo/functions/fnc_playerSingletonSave.sqf
Labels: enhancement, needs testing

#440 Fix Apollo name saving
  addons/apollo/XEH_postInitServer.sqf
  addons/apollo/functions/fnc_handleDisconnect.sqf
  addons/apollo/functions/fnc_playerSingletonSave.sqf
Labels: bug fix

#441 Fix Shooting Range accuracy tracking
  addons/shootingrange/functions/fnc_start.sqf
Labels: bug fix

#442 Make Bodybags Carryable
  addons/bodybag/CfgVehicles.hpp
Labels: enhancement

#444 Fix Apollo name saving server profile name instead of client
  addons/apollo/XEH_postInitServer.sqf
  addons/apollo/functions/fnc_playerLoadClient.sqf
  addons/apollo/functions/fnc_playerSaveClient.sqf
Labels: bug fix

#443 CUP ACE3 Hearing - Fix updating base class
  optionals/cup_ace_hearing/CfgWeapons.hpp
Labels: enhancement

#445 Add example Insurgents gear mission config
  addons/insurgents/README.md
Labels: documentation

#446 Fix fatigue duty increase in crouch-walk
  addons/fatigue/XEH_postInit.sqf
Labels: bug fix
