Repository Theseus-Aegis/Mods, pull requests merged in 2020-02, with the labels that each got.

#425 No Actions - Fix `LightOff` inheritance
  addons/noactions/CfgActions.hpp
Labels: bug fix

#426 Fatigue - Fix missing file and ignore on HC
  addons/fatigue/CfgEventHandlers.hpp
  addons/fatigue/XEH_postInit.sqf
Labels: bug fix, ignore changelog

#427 Armory - Add Export Loadout
  addons/armory/Dialog.hpp
  addons/armory/UI/btnExport.paa
  addons/armory/XEH_PREP.hpp
  addons/armory/functions/fnc_dialogControl.sqf
  addons/armory/functions/fnc_exportLoadout.sqf
  addons/armory/script_component.hpp
  addons/armory/stringtable.xml
Labels: feature request

#428 Apollo - Fix saving on loadout change (CBA 3.14.0)
  addons/apollo/functions/fnc_playerLoadClient.sqf
  addons/apollo/functions/fnc_playerSaveClient.sqf
Labels: bug fix

#429 Medical - Balance Painkillers for Rewrite
  addons/medical/ACE_Medical_Actions.hpp
Labels: enhancement
