Repository Theseus-Aegis/Mods, pull requests merged in 2020-11, with the labels that each got.

#468 Update Autotest AI amount warning
  addons/mission_autotest/script_component.hpp
Labels: task

#462 Add servers component
  addons/servers/$PBOPREFIX$
  addons/servers/CfgEventHandlers.hpp
  addons/servers/CfgMainMenuSpotlight.hpp
  addons/servers/README.md
  addons/servers/XEH_PREP.hpp
  addons/servers/XEH_preInit.sqf
  addons/servers/XEH_preStart.sqf
  addons/servers/config.cpp
  addons/servers/functions/fnc_joinServer.sqf
  addons/servers/functions/script_component.hpp
  addons/servers/script_component.hpp
  addons/servers/stringtable.xml
  addons/servers/ui/spotlight_theseus.paa
Labels: feature request

#470 Update spotlight images
  addons/servers/CfgMainMenuSpotlight.hpp
  addons/servers/ui/spotlight_contracts.paa
  addons/servers/ui/spotlight_olympus.paa
  addons/servers/ui/spotlight_theseus.paa
Labels: enhancement

#471 CBA Settings - Update Night Vision and Bodybag Settings
  addons/cba_settings/cba_settings.sqf
Labels: setting

#472 CBA Settings - Revert Bodybag setting
  addons/cba_settings/cba_settings.sqf
Labels: setting
