Repository Theseus-Aegis/Mods, pull requests merged in 2020-09, with the labels that each got.

#453 TBAN Armed - Fix quoting
  optionals/tban_armed/script_component.hpp
Labels: bug fix

#454 Insurgents - Remove Side Restrictions From Uniforms
  addons/insurgents/CfgVehicles.hpp
Labels: cleanup

#455 Update Heavy Lifter definitions for CUP 1.15.0
  optionals/compat_cup_vehicles/CfgVehicles.hpp
  optionals/compat_cup_vehicles/config.cpp
Labels: compatibility, task

#451 Add Supplies Component
  addons/armory/CfgVehicles.hpp
  addons/armory/UI/tac_locker_ca.jpg
  addons/main/CfgEditorCategories.hpp
  addons/main/config.cpp
  addons/main/stringtable.xml
  addons/supplies/$PBOPREFIX$
  addons/supplies/CfgEventHandlers.hpp
  addons/supplies/CfgVehicles.hpp
  addons/supplies/XEH_PREP.hpp
  addons/supplies/XEH_preInit.sqf
  addons/supplies/XEH_preStart.sqf
  addons/supplies/config.cpp
  addons/supplies/data/launchers_sign_co.paa
  addons/supplies/data/launchers_texture_co.paa
  addons/supplies/data/supply_base_texture_co.paa
  addons/supplies/data/supply_engineer_ca.paa
  addons/supplies/data/supply_medical_ca.paa
  addons/supplies/data/supply_recruit_ca.paa
  addons/supplies/functions/fnc_medicalArsenal.sqf
  addons/supplies/functions/script_component.hpp
  addons/supplies/script_component.hpp
  addons/supplies/stringtable.xml
  addons/supplies/ui/supplies_Engineer.jpg
  addons/supplies/ui/supplies_Launchers.jpg
  addons/supplies/ui/supplies_Medic.jpg
  addons/supplies/ui/supplies_Recruit.jpg
  optionals/compat_amp/$PBOPREFIX$
  optionals/compat_amp/CfgVehicles.hpp
  optionals/compat_amp/config.cpp
  optionals/compat_amp/script_component.hpp
  optionals/compat_cup_weapons/$PBOPREFIX$
  optionals/compat_cup_weapons/CfgVehicles.hpp
  optionals/compat_cup_weapons/config.cpp
  optionals/compat_cup_weapons/script_component.hpp
Labels: feature request

#456 Expand Random Insurgents
  addons/insurgents/CfgVehicles.hpp
  addons/insurgents/config.cpp
  addons/insurgents/stringtable.xml
Labels: enhancement

#457 Expand Supplies & CUP Compat
  addons/supplies/CfgVehicles.hpp
  optionals/compat_cup_weapons/CfgVehicles.hpp
  optionals/compat_cup_weapons/config.cpp
Labels: enhancement

#458 CUP Weapons Compat - Fix Missing Inheritance Class
  optionals/compat_cup_weapons/CfgVehicles.hpp
Labels: bug fix
