Repository Theseus-Aegis/Mods, pull requests merged in 2021-02, with the labels that each got.

#476 Supplies - Add VIP Protective Gear Box
  addons/supplies/CfgVehicles.hpp
  addons/supplies/config.cpp
  addons/supplies/data/supply_vip_ca.paa
  addons/supplies/stringtable.xml
  addons/supplies/ui/supplies_VIP.jpg
  optionals/compat_tacs/$PBOPREFIX$
  optionals/compat_tacs/CfgVehicles.hpp
  optionals/compat_tacs/config.cpp
  optionals/compat_tacs/script_component.hpp
Labels: enhancement

#479 CBA Settings - Require Engineer to repair vehicles
  addons/cba_settings/cba_settings.sqf
Labels: setting

#478 Armory - Fix ghost button
  addons/armory/functions/fnc_dialogControl_main.sqf
Labels: bug fix

#481 Fix remaining quoting warnings
  addons/armory/Dialog.hpp
  addons/armory/script_component.hpp
  addons/mission_autotest/CfgEden.hpp
  addons/ratelmarker/markerMenu.hpp
Labels: bug fix

#480 Supplies - Move to GTArmory
  addons/supplies/CfgVehicles.hpp
  addons/supplies/README.md
  addons/supplies/XEH_preInit.sqf
  addons/supplies/config.cpp
  addons/supplies/data/launchers_sign_co.paa
  addons/supplies/data/launchers_texture_co.paa
  addons/supplies/data/supply_base_texture_co.paa
  addons/supplies/data/supply_engineer_ca.paa
  addons/supplies/data/supply_medical_ca.paa
  addons/supplies/data/supply_recruit_ca.paa
  addons/supplies/data/supply_vip_ca.paa
  addons/supplies/functions/fnc_medicalArsenal.sqf
  addons/supplies/script_component.hpp
  addons/supplies/stringtable.xml
  addons/supplies/ui/supplies_Engineer.jpg
  addons/supplies/ui/supplies_Launchers.jpg
  addons/supplies/ui/supplies_Medic.jpg
  addons/supplies/ui/supplies_Recruit.jpg
  addons/supplies/ui/supplies_VIP.jpg
  optionals/compat_cup_weapons/$PBOPREFIX$
  optionals/compat_cup_weapons/CfgVehicles.hpp
  optionals/compat_cup_weapons/config.cpp
  optionals/compat_cup_weapons/script_component.hpp
  optionals/compat_tacs/$PBOPREFIX$
  optionals/compat_tacs/CfgVehicles.hpp
  optionals/compat_tacs/config.cpp
  optionals/compat_tacs/script_component.hpp
Labels: cleanup, enhancement

#482 CBA Settings - Require cardiac arrest for death
  addons/cba_settings/cba_settings.sqf
Labels: setting

#484 CBA Settings - Refuel hose length from 12m to 20m
  addons/cba_settings/cba_settings.sqf
Labels: setting

#483 Apollo - Save vehicle lock state & Customization
  addons/apollo/functions/fnc_vehicleLoad.sqf
  addons/apollo/functions/fnc_vehicleSingletonSave.sqf
Labels: feature request

#485 Difficulties - Disable Group Commands
  addons/difficulties/CfgDifficultyPresets.hpp
Labels: enhancement
