Repository Theseus-Aegis/Mods, pull requests merged in 2022-10, with the labels that each got.

#533 CBA Settings - Set AI Damage Threshold to 0.6
  addons/cba_settings/cba_settings.sqf
Labels: setting

#532 Heavy Lifter - Make Dynamic and Add API
  addons/heavylifter/CfgVehicles.hpp
  addons/heavylifter/XEH_PREP.hpp
  addons/heavylifter/XEH_postInit.sqf
  addons/heavylifter/XEH_preInit.sqf
  addons/heavylifter/functions/fnc_addActions.sqf
  addons/heavylifter/functions/fnc_canAttach.sqf
  addons/heavylifter/functions/fnc_canDetach.sqf
  addons/heavylifter/functions/fnc_makeLiftable.sqf
  addons/heavylifter/functions/fnc_prepare.sqf
  addons/heavylifter/functions/fnc_progress.sqf
  addons/heavylifter/functions/fnc_unprepare.sqf
Labels: enhancement, bug fix

#534 Apollo Client - Handle request error gracefully and optimize
  extensions/Cargo.lock
  extensions/apollo-client/Cargo.toml
  extensions/apollo-client/src/lib.rs
  extensions/apollo-client/src/main.rs
Labels: enhancement

#536 Difficulties - Set AI skill to 1.0 and allow maximum Spot Distance and Time in Theseus difficulty
  addons/difficulties/CfgAILevelPresets.hpp
  addons/difficulties/CfgAISkill.hpp
  addons/difficulties/CfgDifficultyPresets.hpp
Labels: enhancement

#537 Insurgents - Expand groups
  addons/insurgents/CfgGroups.hpp
  addons/insurgents/groups/blufor.hpp
  addons/insurgents/groups/independent.hpp
  addons/insurgents/groups/opfor.hpp
  addons/insurgents/stringtable.xml
Labels: enhancement
