Repository Theseus-Aegis/Mods, pull requests merged in 2022-09, with the labels that each got.

#527 Apollo - Add ThingX (PhysX objects) to vehicle classes
  addons/apollo/functions/fnc_vehicleSingletonSave.sqf
Labels: enhancement, compatibility

#529 Settings - Update for ACE3 v3.15.1
  addons/cba_settings/cba_settings.sqf
  addons/main/script_mod.hpp
Labels: setting

#528 Insurgents - Change static chances to settings
  addons/insurgents/CfgVehicles.hpp
  addons/insurgents/XEH_preInit.sqf
  addons/insurgents/functions/fnc_randomizeGear.sqf
  addons/insurgents/initSettings.sqf
  addons/insurgents/script_component.hpp
  addons/insurgents/stringtable.xml
Labels: feature request
