Repository Theseus-Aegis/Mods, pull requests merged in 2022-04, with the labels that each got.

#511 Apollo - Convert JNI extension calls to `arma-rs` supported format
  addons/apollo/XEH_postInitServer.sqf
  addons/apollo/functions/fnc_invokeJavaMethod.sqf
Labels: task

#513 Remove slingloading locality fix
  addons/slingload/$PBOPREFIX$
  addons/slingload/CfgEventHandlers.hpp
  addons/slingload/README.md
  addons/slingload/XEH_postInitServer.sqf
  addons/slingload/config.cpp
  addons/slingload/script_component.hpp
Labels: cleanup

#510 Project Infinite - Add ACE ballistic values to 300WM / 338LM
  optionals/bnae_falkor_compat_ace/CfgAmmo.hpp
  optionals/bnae_falkor_compat_ace/README.md
  optionals/bnae_falkor_compat_ace/config.cpp
  optionals/bnae_trg42_compat_ace/CfgAmmo.hpp
  optionals/bnae_trg42_compat_ace/README.md
  optionals/bnae_trg42_compat_ace/config.cpp
Labels: enhancement

#514 Supplies - Apply traits on load
  addons/supplies/CfgEventHandlers.hpp
  addons/supplies/XEH_PREP.hpp
  addons/supplies/XEH_postInitClient.sqf
  addons/supplies/XEH_postInitServer.sqf
  addons/supplies/XEH_preInit.sqf
  addons/supplies/config.cpp
  addons/supplies/functions/fnc_loadTraits.sqf
  addons/supplies/functions/fnc_traitActions.sqf
Labels: enhancement

#467 Rewrite extensions in Rust
  .github/workflows/extensions.yml
  .gitignore
  README.md
  addons/apollo/XEH_PREP.hpp
  addons/apollo/functions/fnc_getPlayerInfo.sqf
  addons/apollo/functions/fnc_handleExtMultipartReturn.sqf
  addons/apollo/functions/fnc_playerLoadClient.sqf
  addons/apollo/script_component.hpp
  addons/armory/functions/fnc_getDataChronos.sqf
  extensions/.gitignore
  extensions/CMakeLists.txt
  extensions/CMakeModules/cxx_compiler_functions.cmake
  extensions/Cargo.lock
  extensions/Cargo.toml
  extensions/apollo-client/Cargo.toml
  extensions/apollo-client/src/lib.rs
  extensions/apollo-client/src/main.rs
  extensions/build/.gitignore
  extensions/src/apollo_client/CMakeLists.txt
  extensions/src/apollo_client/dllmain.cpp
  extensions/src/common/CMakeLists.txt
  extensions/src/common/constants.h
  extensions/src/common/easylogging++.cc
  extensions/src/common/easylogging++.h
  extensions/src/common/logging.hpp
  extensions/src/common/shared.hpp
  extensions/src/common/tac_version_win32.rc.in
  extensions/src/common/targetver.h
  extensions/src/common/version.h
  extensions/vcproj/.gitignore
  extensions/vcproj64/.gitignore
  hemtt.toml
  tac_apollo_client.dll
  tac_apollo_client_x64.dll
Labels: feature request, tools

#517 Armory - Fix quantity type for use of `parseSimpleArray`
  addons/apollo/functions/fnc_playerLoadClient.sqf
  addons/armory/functions/fnc_dialogControl_populateList.sqf
  addons/armory/functions/fnc_getBoxContents.sqf
  addons/armory/functions/fnc_subtractData.sqf
Labels: bug fix

#518 Armory - Fix quantity type error on take action
  addons/armory/README.md
  addons/armory/functions/fnc_subtractData.sqf
Labels: bug fix

#519 Extensions - Handle non-ASCII characters gracefully
  extensions/apollo-client/src/lib.rs
  extensions/apollo-client/src/main.rs
Labels: bug fix

#520 Apollo - Wrap extension calls in a helper function
  addons/apollo/XEH_PREP.hpp
  addons/apollo/functions/fnc_callExt.sqf
  addons/apollo/functions/fnc_getPlayerInfo.sqf
  addons/apollo/functions/fnc_handleExtMultipartReturn.sqf
  addons/apollo/functions/fnc_playerLoadClient.sqf
  addons/armory/functions/fnc_getDataChronos.sqf
Labels: enhancement

#521 Heavy Lifter - Remove redundant select
  addons/heavylifter/functions/fnc_exportConfig.sqf
Labels: cleanup
