Repository Theseus-Aegis/Mods, pull requests merged in 2022-12, with the labels that each got.

#535 Add functions library
  addons/insurgents/XEH_preInit.sqf
  addons/mission/$PBOPREFIX$
  addons/mission/CfgEventHandlers.hpp
  addons/mission/README.md
  addons/mission/XEH_PREP.hpp
  addons/mission/XEH_postInit.sqf
  addons/mission/XEH_preInit.sqf
  addons/mission/XEH_preStart.sqf
  addons/mission/config.cpp
  addons/mission/functions/fnc_aar.sqf
  addons/mission/functions/fnc_baseSpectator.sqf
  addons/mission/functions/fnc_bomber.sqf
  addons/mission/functions/fnc_caves.sqf
  addons/mission/functions/fnc_collectIntel.sqf
  addons/mission/functions/fnc_connectBatteryToDefusable.sqf
  addons/mission/functions/fnc_d30Strike.sqf
  addons/mission/functions/fnc_forceShooting.sqf
  addons/mission/functions/fnc_godMode.sqf
  addons/mission/functions/fnc_hunt.sqf
  addons/mission/functions/fnc_monitorUnits.sqf
  addons/mission/functions/fnc_mortarStrike.sqf
  addons/mission/functions/fnc_reaction.sqf
  addons/mission/functions/fnc_reinforcements.sqf
  addons/mission/functions/fnc_respiratorEffects.sqf
  addons/mission/functions/fnc_surrender.sqf
  addons/mission/functions/fnc_switchAction.sqf
  addons/mission/functions/fnc_teleport.sqf
  addons/mission/functions/fnc_toggleLights.sqf
  addons/mission/functions/fnc_unconscious.sqf
  addons/mission/functions/script_component.hpp
  addons/mission/script_component.hpp
  addons/mission/script_macros_mission.hpp
Labels: feature request

#538 Medical - Add Fatal Injuries Cardiac Arrest Time Coefficient
  addons/cba_settings/cba_settings.sqf
  addons/medical/CfgEventHandlers.hpp
  addons/medical/XEH_postInit.sqf
  addons/medical/XEH_preInit.sqf
  addons/medical/config.cpp
  addons/medical/initSettings.sqf
  addons/medical/stringtable.xml
Labels: feature request

#543 Mission - Cleanup examples
  addons/insurgents/functions/fnc_randomizeGear.sqf
  addons/mission/functions/fnc_aar.sqf
  addons/mission/functions/fnc_baseSpectator.sqf
  addons/mission/functions/fnc_bomber.sqf
  addons/mission/functions/fnc_caves.sqf
  addons/mission/functions/fnc_collectIntel.sqf
  addons/mission/functions/fnc_connectBatteryToDefusable.sqf
  addons/mission/functions/fnc_d30Strike.sqf
  addons/mission/functions/fnc_forceShooting.sqf
  addons/mission/functions/fnc_godMode.sqf
  addons/mission/functions/fnc_hunt.sqf
  addons/mission/functions/fnc_monitorUnits.sqf
  addons/mission/functions/fnc_mortarStrike.sqf
  addons/mission/functions/fnc_reaction.sqf
  addons/mission/functions/fnc_reinforcements.sqf
  addons/mission/functions/fnc_respiratorEffects.sqf
  addons/mission/functions/fnc_surrender.sqf
  addons/mission/functions/fnc_switchAction.sqf
  addons/mission/functions/fnc_teleport.sqf
  addons/mission/functions/fnc_toggleLights.sqf
  addons/mission/functions/fnc_unconscious.sqf
Labels: cleanup, ignore changelog

#542 Mission - Add jamming script
  addons/mission/XEH_PREP.hpp
  addons/mission/functions/fnc_jam.sqf
Labels: feature request

#544 Mission - Fix Jam script ACRE2 mod check
  addons/mission/functions/fnc_jam.sqf
Labels: bug fix
