Repository Theseus-Aegis/Mods, pull requests merged in 2023-09, with the labels that each got.

#626 General - Streamline logo
  addons/main/UI/logo_tac_ca.paa
  addons/main/UI/logo_tac_small_ca.paa
  extras/assets/logo/TAC-Logo.jpg
  extras/assets/logo/TAC-Logo.png
  extras/assets/logo/TAC-Logo_old.jpg
  extras/assets/logo/TAC-Logo_old.png
  logo_tac_ca.paa
  logo_tac_small_ca.paa
Labels: enhancement

#618 General - Streamline branding
  .github/workflows/arma.yml
  .hemtt/hooks/post_release/01_rename_zip.rhai
  .hemtt/project.toml
  AUTHORS.txt
  README.md
  addons/main/$PBOPREFIX$
  addons/main/config.cpp
  addons/main/stringtable.xml
  extensions/apollo-client/Cargo.toml
  mod.cpp
Labels: cleanup

#630 Various - Cleanup `requiredAddons`
  addons/acre/config.cpp
  addons/breaching/config.cpp
  addons/cup/config.cpp
  addons/insurgents/config.cpp
  addons/milgp/config.cpp
  addons/ui_tweaks/config.cpp
Labels: cleanup, ignore changelog

#632 Mission - Add Spectators God Mode group
  addons/mission/functions/fnc_godMode.sqf
Labels: enhancement

#636 Radios - Fix stop working only for player stopping it
  addons/radios/XEH_postInitClient.sqf
  addons/radios/functions/fnc_stop.sqf
Labels: bug fix

#628 Western Sahara - Remove ACE No Uniform Restrictions
  addons/ws/$PBOPREFIX$
  addons/ws/CfgVehicles.hpp
  addons/ws/README.md
  addons/ws/config.cpp
  addons/ws/script_component.hpp
Labels: cleanup

#629 Settings - Enable Auto-Equip NVGs and FRIES
  addons/cba_settings/cba_settings.sqf
  addons/main/script_mod.hpp
Labels: setting

#633 Settings - Disable Grave Digging
  addons/cba_settings/cba_settings.sqf
Labels: setting

#627 Mission - Remove automatic NVG assignment
  addons/mission/XEH_PREP.hpp
  addons/mission/XEH_postInit.sqf
  addons/mission/XEH_preInit.sqf
  addons/mission/functions/fnc_assignNVG.sqf
  addons/mission/functions/fnc_assignNVGpfh.sqf
Labels: cleanup

#635 Mission - Add Ping function
  addons/mission/XEH_PREP.hpp
  addons/mission/XEH_postInit.sqf
  addons/mission/functions/fnc_ping.sqf
Labels: feature request

#637 General - Fix macro redefinitions and add missing beautified component names
  addons/insurgents/script_component.hpp
  addons/mission/script_component.hpp
Labels: bug fix
