Repository Theseus-Aegis/Mods, pull requests merged in 2023-12, with the labels that each got.

#655 General - Fix commas which should be semi-colons
  addons/radios/functions/fnc_init.sqf
  addons/shootingrange/functions/fnc_checkConfig.sqf
Labels: bug fix

#657 Extensions - Update dependencies
  extensions/Cargo.lock
Labels: dependencies

#660 Mission - Add Hunt groups to monitor units
  addons/mission/functions/fnc_monitorUnits.sqf
Labels: enhancement

#659 Mission - Add Door Lock function
  addons/mission/XEH_PREP.hpp
  addons/mission/functions/fnc_lockDoors.sqf
Labels: feature request
