Repository Theseus-Aegis/Mods, pull requests merged in 2023-06, with the labels that each got.

#579 Difficulties - Add configurable Armor Accuracy Factor
  addons/cba_settings/cba_settings.sqf
  addons/difficulties/CfgEventHandlers.hpp
  addons/difficulties/XEH_PREP.hpp
  addons/difficulties/XEH_postInit.sqf
  addons/difficulties/XEH_preInit.sqf
  addons/difficulties/XEH_preStart.sqf
  addons/difficulties/config.cpp
  addons/difficulties/functions/fnc_setUnitAccuracy.sqf
  addons/difficulties/functions/script_component.hpp
  addons/difficulties/initSettings.sqf
  addons/difficulties/stringtable.xml
Labels: feature request, setting

#583 Mission - Rewrite `switchAction`
  addons/mission/functions/fnc_switchAction.sqf
Labels: enhancement

#585 Mission - Expand Respirator Effects
  addons/mission/functions/fnc_respiratorEffects.sqf
Labels: enhancement

#586 Mission - Return particle emitters in Contamination Gas
  addons/mission/functions/fnc_contaminationGas.sqf
Labels: enhancement

#588 Difficulties / Mission - Fix Typos
  addons/difficulties/functions/fnc_setUnitAccuracy.sqf
  addons/mission/functions/fnc_dialogue.sqf
Labels: ignore changelog

#587 UI Tweaks - Collapse categories by default in Eden
  addons/ui_tweaks/Display3DEN.hpp
  addons/ui_tweaks/config.cpp
Labels: enhancement

#589 Mission - Add Damage Per Tick and Damage Tick Rate to Respirator Effects
  addons/mission/functions/fnc_respiratorEffects.sqf
Labels: enhancement

#590 Insurgents/Mission - Remove CUP
  addons/insurgents/CfgInsurgentGear.hpp
  addons/insurgents/README.md
  addons/mission/XEH_PREP.hpp
  addons/mission/functions/fnc_d30Strike.sqf
Labels: enhancement, cleanup

#593 Optionals - Add Aegis ACE Hearing
  optionals/aegis_ace_hearing/$PBOPREFIX$
  optionals/aegis_ace_hearing/CfgWeapons.hpp
  optionals/aegis_ace_hearing/README.md
  optionals/aegis_ace_hearing/config.cpp
  optionals/aegis_ace_hearing/script_component.hpp
Labels: feature request

#594 Optionals - Add Aegis No Uniform Restrictions
  optionals/aegis_nouniformrestrictions/$PBOPREFIX$
  optionals/aegis_nouniformrestrictions/CfgVehicles.hpp
  optionals/aegis_nouniformrestrictions/README.md
  optionals/aegis_nouniformrestrictions/config.cpp
  optionals/aegis_nouniformrestrictions/script_component.hpp
Labels: feature request

#599 Mission - Add death failsafe and optional method of disabling sounds to `respiratorEffects`
  addons/mission/functions/fnc_respiratorEffects.sqf
Labels: bug fix

#598 Extensions - Update dependencies
  extensions/Cargo.lock
Labels: enhancement

#592 MELB Tweaks - Rewrite scripts and Add GEOLOCK
  optionals/melb_ace_fastroping/$PBOPREFIX$
  optionals/melb_ace_fastroping/CfgVehicles.hpp
  optionals/melb_ace_fastroping/README.md
  optionals/melb_ace_fastroping/config.cpp
  optionals/melb_ace_fastroping/script_component.hpp
  optionals/melb_tweaks/CfgEventHandlers.hpp
  optionals/melb_tweaks/CfgVehicles.hpp
  optionals/melb_tweaks/README.md
  optionals/melb_tweaks/RscInGameUI.hpp
  optionals/melb_tweaks/XEH_PREP.hpp
  optionals/melb_tweaks/XEH_postInitClient.sqf
  optionals/melb_tweaks/XEH_preInit.sqf
  optionals/melb_tweaks/XEH_preStart.sqf
  optionals/melb_tweaks/config.cpp
  optionals/melb_tweaks/functions/fnc_canToggleMFD.sqf
  optionals/melb_tweaks/functions/fnc_geolock.sqf
  optionals/melb_tweaks/functions/fnc_handleFLIR.sqf
  optionals/melb_tweaks/functions/fnc_loadMFD.sqf
  optionals/melb_tweaks/functions/fnc_setMFDMode.sqf
  optionals/melb_tweaks/functions/fnc_setMFDZoom.sqf
  optionals/melb_tweaks/functions/fnc_setupMFD.sqf
  optionals/melb_tweaks/functions/fnc_toggleMFD.sqf
  optionals/melb_tweaks/functions/fnc_unloadMFD.sqf
  optionals/melb_tweaks/functions/script_component.hpp
  optionals/melb_tweaks/script_component.hpp
Labels: enhancement, needs testing, feature request

#597 Add Breaching
  addons/breaching/$PBOPREFIX$
  addons/breaching/CfgAmmo.hpp
  addons/breaching/CfgEventHandlers.hpp
  addons/breaching/CfgMagazines.hpp
  addons/breaching/CfgVehicles.hpp
  addons/breaching/CfgWeapons.hpp
  addons/breaching/README.md
  addons/breaching/XEH_PREP.hpp
  addons/breaching/XEH_postInit.sqf
  addons/breaching/XEH_preInit.sqf
  addons/breaching/XEH_preStart.sqf
  addons/breaching/config.cpp
  addons/breaching/functions/fnc_breach.sqf
  addons/breaching/functions/fnc_handleBreachDeleted.sqf
  addons/breaching/functions/fnc_setupBreach.sqf
  addons/breaching/functions/script_component.hpp
  addons/breaching/script_component.hpp
  addons/breaching/stringtable.xml
Labels: needs testing, feature request

#600 Remove Optional AMP (Breaching Charge) Compatibility
  optionals/compat_amp/$PBOPREFIX$
  optionals/compat_amp/CfgVehicles.hpp
  optionals/compat_amp/config.cpp
  optionals/compat_amp/script_component.hpp
Labels: cleanup
