Repository Theseus-Aegis/Mods, pull requests merged in 2023-05, with the labels that each got.

#564 Mission - Optimize Hunt target selection
  addons/mission/functions/fnc_hunt.sqf
  addons/mission/functions/fnc_reinforcements.sqf
Labels: enhancement

#565 Mission - Optimize Bomber target selection
  addons/mission/functions/fnc_bomber.sqf
Labels: enhancement

#566 Mission - Add support for custom icons in Teleport
  addons/mission/functions/fnc_teleport.sqf
Labels: enhancement

#567 Mission - Fix players included in Monitor Units AI counting
  addons/mission/functions/fnc_monitorUnits.sqf
Labels: bug fix

#570 Mission - Add Ground Fog
  addons/mission/XEH_PREP.hpp
  addons/mission/functions/fnc_groundFog.sqf
Labels: feature request

#571 Mission - Add Earthquake
  addons/mission/XEH_PREP.hpp
  addons/mission/functions/fnc_earthquake.sqf
Labels: feature request

#573 Tools - Update SQF validator
  tools/sqf_validator.py
Labels: tools

#572 Mission - Fix Groundfog condition check
  addons/mission/functions/fnc_groundFog.sqf
Labels: bug fix, ignore changelog

#569 Mission - Rework Respirator Effects and Add Contamination Gas
  addons/mission/XEH_PREP.hpp
  addons/mission/functions/fnc_contaminationGas.sqf
  addons/mission/functions/fnc_respiratorEffects.sqf
Labels: enhancement, feature request

#576 Update ACE3 translation guide URL
  tools/deploy.py
Labels: translation, tools

#575 Mission - Fix incorrect Monitor Units counts with players
  addons/mission/functions/fnc_monitorUnits.sqf
Labels: bug fix

#577 Mission - Fix Bomber target checking
  addons/mission/functions/fnc_bomber.sqf
Labels: bug fix

#581 Mission - Add `countAlive` function
  addons/mission/XEH_PREP.hpp
  addons/mission/functions/fnc_countAlive.sqf
Labels: feature request

#582 Medical - Fix stringtable entries
  addons/medical/stringtable.xml
Labels: bug fix

#580 Mission - Streamline and add on-screen logging
  addons/mission/XEH_PREP.hpp
  addons/mission/functions/fnc_baseSpectator.sqf
  addons/mission/functions/fnc_contaminationGas.sqf
  addons/mission/functions/fnc_earthquake.sqf
  addons/mission/functions/fnc_jam.sqf
  addons/mission/functions/fnc_log.sqf
  addons/mission/functions/fnc_reaction.sqf
  addons/mission/functions/fnc_reinforcements.sqf
  addons/mission/script_component.hpp
Labels: enhancement
