Repository Theseus-Aegis/Mods, pull requests merged in 2023-01, with the labels that each got.

#548 Mission - Move mission type verification to template
  addons/mission/XEH_postInit.sqf
Labels: bug fix

#550 Mission - Fix Auto-AAR
  addons/mission/functions/fnc_aar.sqf
Labels: bug fix

#551 Optionals - Add Western Sahara No Uniform Restriction
  optionals/ws_nouniformrestrictions/$PBOPREFIX$
  optionals/ws_nouniformrestrictions/CfgVehicles.hpp
  optionals/ws_nouniformrestrictions/README.md
  optionals/ws_nouniformrestrictions/config.cpp
  optionals/ws_nouniformrestrictions/script_component.hpp
Labels: feature request

#552 Insurgents - Add compatibility for reinforcements
  addons/insurgents/functions/fnc_randomizeGear.sqf
Labels: compatibility

#554 Apollo - Fix vehicle saving (invalid class passed to extension)
  addons/apollo/functions/fnc_vehicleSingletonSave.sqf
Labels: bug fix

#555 Mission - Add Rallying to Surrender
  addons/mission/functions/fnc_surrender.sqf
Labels: enhancement
