Repository Theseus-Aegis/Mods, pull requests merged in 2023-08, with the labels that each got.

#603 Servers - Remove S.O.G. Prairie Fire and Spearhead 1944 from Main Menu Spotlight
  addons/servers/CfgMainMenuSpotlight.hpp
Labels: enhancement

#606 Mission - Add D30 functionality to Mortar Strike
  addons/mission/functions/fnc_mortarStrike.sqf
Labels: enhancement

#605 Mission - Remove `taskDefend` & `taskPatrol` functions
  addons/mission/XEH_PREP.hpp
  addons/mission/functions/fnc_taskDefend.sqf
  addons/mission/functions/fnc_taskPatrol.sqf
Labels: cleanup

#604 Mission Autotest - Add AP Units, Group size and Vehicle checks
  addons/mission_autotest/CfgEden.hpp
  addons/mission_autotest/XEH_PREP.hpp
  addons/mission_autotest/functions/fnc_testAPAmount.sqf
  addons/mission_autotest/functions/fnc_testAPCAmount.sqf
  addons/mission_autotest/functions/fnc_testGroupSizes.sqf
  addons/mission_autotest/functions/fnc_testTrackedAmount.sqf
  addons/mission_autotest/script_component.hpp
  addons/mission_autotest/stringtable.xml
Labels: feature request

#608 Mission - Add AI Sleeping function
  addons/mission/XEH_PREP.hpp
  addons/mission/functions/fnc_setSleeping.sqf
Labels: feature request

#611 Mission - Fix `setSleeping` function
  addons/mission/functions/fnc_setSleeping.sqf
Labels: bug fix, ignore changelog

#609 Mission - Add Download Intel function
  addons/mission/XEH_PREP.hpp
  addons/mission/functions/fnc_downloadIntel.sqf
Labels: feature request

#612 Insurgents - Use HashMap instead of Namespace
  addons/insurgents/XEH_preInit.sqf
  addons/insurgents/script_component.hpp
Labels: enhancement

#614 Add performance setting to Disable Remote Sensors on Clients
  addons/performance/$PBOPREFIX$
  addons/performance/CfgEventHandlers.hpp
  addons/performance/README.md
  addons/performance/XEH_preInit.sqf
  addons/performance/config.cpp
  addons/performance/initSettings.sqf
  addons/performance/script_component.hpp
  addons/performance/stringtable.xml
Labels: feature request

#613 Add vanilla country markers to flag poles
  addons/flags/$PBOPREFIX$
  addons/flags/CfgVehicles.hpp
  addons/flags/README.md
  addons/flags/config.cpp
  addons/flags/script_component.hpp
Labels: feature request

#615 Mission - Add automatic AI NVG assignment
  addons/mission/XEH_PREP.hpp
  addons/mission/XEH_postInit.sqf
  addons/mission/XEH_preInit.sqf
  addons/mission/functions/fnc_assignNVG.sqf
  addons/mission/functions/fnc_assignNVGpfh.sqf
Labels: feature request

#617 Mission - Add Icon to download intel function
  addons/mission/functions/fnc_downloadIntel.sqf
Labels: enhancement, ignore changelog

#616 Add radios (music in vehicles) framework
  addons/radios/$PBOPREFIX$
  addons/radios/CfgEventHandlers.hpp
  addons/radios/CfgVehicles.hpp
  addons/radios/README.md
  addons/radios/XEH_PREP.hpp
  addons/radios/XEH_postInitClient.sqf
  addons/radios/XEH_preInit.sqf
  addons/radios/XEH_preStart.sqf
  addons/radios/config.cpp
  addons/radios/functions/fnc_init.sqf
  addons/radios/functions/fnc_play.sqf
  addons/radios/functions/fnc_stop.sqf
  addons/radios/functions/script_component.hpp
  addons/radios/initSettings.sqf
  addons/radios/script_component.hpp
  addons/radios/stringtable.xml
  addons/radios/ui/musicStart_ca.paa
  addons/radios/ui/musicStop_ca.paa
  extras/assets/icons/Actions/musicStart.xcf
  extras/assets/icons/Actions/musicStop.xcf
Labels: feature request

#619 Optional Project Infinite RK95 - Fix Rail UBC
  optionals/bnae_rk95_compat_ace/CfgWeapons.hpp
Labels: bug fix

#620 Apollo - Add Automatic Server Reset
  addons/apollo/XEH_postInitServer.sqf
  addons/apollo/initSettings.sqf
  addons/apollo/stringtable.xml
Labels: feature request

#622 Apollo - Reselect weapon and cleanup unused variables
  addons/apollo/functions/fnc_playerLoadClient.sqf
  addons/apollo/functions/fnc_playerSingletonSave.sqf
Labels: enhancement, cleanup

#624 Apollo - Fix trying to save player with invalid UID
  addons/apollo/functions/fnc_playerSingletonSave.sqf
Labels: bug fix

#625 Settings - Disable NIArms Grip Switch model replacing
  addons/cba_settings/cba_settings.sqf
Labels: setting
