Repository Theseus-Aegis/Mods, pull requests merged in 2024-03, with the labels that each got.

#670 Ping - Fix missing use of `maxSize` argument
  addons/mission/functions/fnc_ping.sqf
Labels: bug fix

#675 Mission - Add Players function
  addons/mission/XEH_PREP.hpp
  addons/mission/functions/fnc_players.sqf
Labels: feature request

#678 Mission - Add disableAI / enableAI events
  addons/mission/XEH_postInit.sqf
Labels: enhancement, bug fix

#673 Mission - Rework Reinforcements
  addons/mission/functions/fnc_reinforcements.sqf
Labels: enhancement

#676 Mission - Rework Mortar Strike
  addons/mission/functions/fnc_mortarStrike.sqf
Labels: enhancement

#679 Mission - Allow units in disableAI / enableAI functions
  addons/mission/functions/fnc_disableAI.sqf
  addons/mission/functions/fnc_enableAI.sqf
Labels: enhancement

#677 Mission - Add Headless Blacklist wrapper function
  addons/mission/XEH_PREP.hpp
  addons/mission/functions/fnc_blacklistHeadless.sqf
Labels: feature request

#681 Headless - Improve position by taking average and removing outliers
  addons/headless/functions/fnc_moveHeadless.sqf
Labels: enhancement, needs testing

#680 Add Headless automatic move with players
  addons/headless/$PBOPREFIX$
  addons/headless/CfgEventHandlers.hpp
  addons/headless/XEH_PREP.hpp
  addons/headless/XEH_preInit.sqf
  addons/headless/XEH_preStart.sqf
  addons/headless/config.cpp
  addons/headless/functions/fnc_moveHeadless.sqf
  addons/headless/initSettings.inc.sqf
  addons/headless/script_component.hpp
  addons/headless/stringtable.xml
  addons/mission/functions/fnc_players.sqf
Labels: feature request

#674 Mission - Alter and fix functions
  addons/mission/XEH_postInit.sqf
  addons/mission/functions/fnc_bomber.sqf
  addons/mission/functions/fnc_hunt.sqf
  addons/mission/functions/fnc_mortarStrike.sqf
  addons/mission/functions/fnc_respiratorEffects.sqf
Labels: enhancement, bug fix

#682 CBA Settings - Alter fatigue settings
  addons/cba_settings/cba_settings.sqf
Labels: setting

#683 Medical - Remove Painkillers
  addons/medical/ACE_Medical_Actions.hpp
  addons/medical/CfgVehicles.hpp
  addons/medical/CfgWeapons.hpp
  addons/medical/README.md
  addons/medical/config.cpp
  addons/medical/stringtable.xml
  addons/medical/ui/painkillers_icon_ca.paa
  addons/medical/ui/painkillers_inventory_ca.paa
Labels: cleanup

#652 Remove CUP Compatibility (merged into ACE3)
  addons/cup/$PBOPREFIX$
  addons/cup/CfgVehicles.hpp
  addons/cup/CfgWeapons.hpp
  addons/cup/README.md
  addons/cup/config.cpp
  addons/cup/script_component.hpp
Labels: cleanup

#684 Apollo - Fix vehicles taking drop damage after spawn
  addons/apollo/functions/fnc_vehicleLoad.sqf
Labels: bug fix
