Repository Theseus-Aegis/Mods, pull requests merged in 2024-04, with the labels that each got.

#685 Headless - Fix Setting Error
  addons/headless/initSettings.inc.sqf
Labels: bug fix, ignore changelog

#687 Extensions - Update dependencies
  extensions/Cargo.lock
Labels: dependencies

#688 Supplies - Fix medical arsenal using old painkiller class
  addons/supplies/functions/fnc_medicalArsenal.sqf
Labels: bug fix

#690 Mission - Fix Ping function never getting deleted
  addons/mission/functions/fnc_ping.sqf
Labels: bug fix

#689 Mission - Fix mortar firing delay
  addons/mission/XEH_postInit.sqf
  addons/mission/functions/fnc_mortarStrike.sqf
Labels: bug fix
