Repository Theseus-Aegis/Mods, pull requests merged in 2024-01, with the labels that each got.

#653 Bodybag - Separate action for Orange bodybag
  addons/bodybag/ACE_Medical_Treatment_Actions.hpp
  addons/bodybag/stringtable.xml
  addons/supplies/functions/fnc_medicalArsenal.sqf
Labels: compatibility

#661 Settings - Remove Fatal Damage Source
  addons/cba_settings/cba_settings.sqf
  addons/main/script_mod.hpp
Labels: cleanup

#648 Gimmick - Add Talking Box
  addons/gimmick/$PBOPREFIX$
  addons/gimmick/CfgEventHandlers.hpp
  addons/gimmick/XEH_PREP.hpp
  addons/gimmick/XEH_postInitClient.sqf
  addons/gimmick/XEH_postInitServer.sqf
  addons/gimmick/XEH_preInit.sqf
  addons/gimmick/XEH_preStart.sqf
  addons/gimmick/config.cpp
  addons/gimmick/functions/fnc_talkingBox.sqf
  addons/gimmick/initSettings.sqf
  addons/gimmick/script_component.hpp
  addons/gimmick/stringtable.xml
Labels: feature request

#663 Mission - Add Car Alarm function
  addons/mission/XEH_PREP.hpp
  addons/mission/functions/fnc_carAlarm.sqf
Labels: feature request

#666 Supplies - Fix Medical Arsenal adding virtual items globally
  addons/supplies/functions/fnc_medicalArsenal.sqf
Labels: bug fix

#665 Mission - Fix Hunt Group not showing count
  addons/mission/XEH_preInit.sqf
  addons/mission/functions/fnc_monitorUnits.sqf
Labels: bug fix

#667 Mission - Add Logging, some additional cleanup
  addons/mission/XEH_PREP.hpp
  addons/mission/functions/fnc_bomber.sqf
  addons/mission/functions/fnc_caves.sqf
  addons/mission/functions/fnc_connectBatteryToDefusable.sqf
  addons/mission/functions/fnc_countAlive.sqf
  addons/mission/functions/fnc_disableAI.sqf
  addons/mission/functions/fnc_enableAI.sqf
  addons/mission/functions/fnc_hunt.sqf
  addons/mission/functions/fnc_reaction.sqf
  addons/mission/functions/fnc_reinforcementWaves.sqf
  addons/mission/functions/fnc_reinforcements.sqf
  addons/mission/functions/fnc_setSleeping.sqf
  addons/mission/functions/fnc_surrender.sqf
Labels: enhancement, bug fix
