Repository Theseus-Aegis/Mods, pull requests merged in 2025-02, with the labels that each got.

#725 Extensions - Update dependencies
  extensions/Cargo.lock
  extensions/apollo-client/Cargo.toml
Labels: dependencies

#726 Mission - Add Ambient Effects function
  addons/mission/XEH_PREP.hpp
  addons/mission/functions/fnc_ambientEffects.sqf
Labels: feature request

#723 Mission - Add Keypad functionality
  addons/mission/RscGUI.hpp
  addons/mission/XEH_PREP.hpp
  addons/mission/config.cpp
  addons/mission/functions/fnc_keypadPress.sqf
  addons/mission/functions/fnc_keypadSetup.sqf
  addons/mission/script_component.hpp
Labels: feature request

#727 General - Fix HEMTT 1.14.3 warnings
  addons/armory/stringtable.xml
  addons/ratelmarker/stringtable.xml
  addons/shootingrange/stringtable.xml
  addons/supplies/stringtable.xml
Labels: enhancement
